version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - tmdbnet
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - tmdbnet
networks:
  tmdbnet:
    driver: bridge
